### ISSUE TITLE
项目打包出来是空白

### ISSUE THREAD

**Issue by delete1226** [tower1229/Vue-Tree-Chart#10]
我把这个npm到我的项目，打包出来是空白，是不是需要有什么配置啊？

**Comment by tower1229** [comment]
安装后只是得到了这个组件，你是安装完了直接运行项目吗，那肯定是空白

**Comment by jfengzzz** [comment]
github上Down下来的demo包，npm run serve运行是能看到的，但是npm run build-bundle打包出来的docs里面的demo文件打开，是空白呢

**Comment by tower1229** [comment]
`npm run build-bundle`是以类库的形式构建，你应该用的是`npm run build`
