### ISSUE TITLE
转为竖着的时候,全部收起的状态,再也展不开了

### ISSUE THREAD

**Issue by iscelinetam** [tower1229/Vue-Tree-Chart#11]
转为竖着的时候,全部收起的状态,再也展不开了

**Comment by tower1229** [comment]
嗯，demo确实有这个问题，这是css样式导致的，你用调试工具看下会发现是根节点遮挡了展开箭头，导致展开箭头无法被点击到。这个横竖切换的样式很难做的通用，生产环境下都要根据实际设计需求调整，这里我就不改了，谢谢你的提醒

**Comment by wrh4585** [comment]
demo中的问题，可以给箭头所在的div设置z-index属性，这样就可以点击到了
