### ISSUE TITLE
请问这个组件有没有更新到最新的Vue3的计划？

### ISSUE THREAD

**Issue by AndyChien1986** [tower1229/Vue-Tree-Chart#19]
请问这个组件有没有更新到最新Vue3+的计划？目前公司内部使用的是Vue3搭建的框架，原先组件内使用的Vue2+的内置变量已经失效或过时，导致组件无法在Vu3+的框架内正常使用。

**Comment by tower1229** [comment]
vue3正式发布后会切换到vue3
