### ISSUE TITLE
mate节点显示异常

### ISSUE THREAD

**Issue by jianlong-sun** [tower1229/Vue-Tree-Chart#20]
使用readme 中example， mate中name、 image_url 无法正常显示 
![QQ截图20210206113519](https://user-images.githubusercontent.com/25893282/107107960-6cbe4700-686f-11eb-905f-873a782c7246.png)

**Comment by jianlong-sun** [comment]
不使用npm，直接使用组件生效

**Comment by agursoy** [comment]
Hi, I tried to import directly from source code but still problem continues.
