### ISSUE TITLE
pls support for vue 3

### ISSUE THREAD

**Issue by soemxui195** [tower1229/Vue-Tree-Chart#21]
I hope new version vue3 of vue tree chart. Tks so much <3

**Comment by tower1229** [comment]
> I hope new version vue3 of vue tree chart. Tks so much <3

I'm waiting for vue3 to really stabilize

**Comment by OuZuYu** [comment]
> > I hope new version vue3 of vue tree chart. Tks so much <3
> 
> I'm waiting for vue3 to really stabilize

It is stable now 😁

**Comment by tower1229** [comment]
> > > I hope new version vue3 of vue tree chart. Tks so much <3
> > 
> > 
> > I'm waiting for vue3 to really stabilize
> 
> It is stable now 😁

OK, I`m working on it

**Comment by tower1229** [comment]
> > > > I hope new version vue3 of vue tree chart. Tks so much <3
> > > 
> > > 
> > > I'm waiting for vue3 to really stabilize
> > 
> > 
> > It is stable now 😁
> 
> OK, I`m working on it

https://github.com/tower1229/Vue-Tree-Chart/tree/vue3
