### ISSUE TITLE
配偶节点显示不正常

### ISSUE THREAD

**Issue by nidegexing** [tower1229/Vue-Tree-Chart#5]
我是通过直接引入TreeChart.vue文件来引入的，没有安装。使用中发现配偶节点不是平行展示的，而是上下展示，见下图
![image](https://user-images.githubusercontent.com/18201505/47194072-88dd0800-d388-11e8-8b4e-bf87c58a705c.png)

**Comment by nidegexing** [comment]
https://refined-x.com/Vue-Tree-Chart/，这个版本是完美的，线条来说。
![image](https://user-images.githubusercontent.com/18201505/47284346-a1178600-d619-11e8-8156-253f39e1e56a.png)
可是我用demo的数据做不出来。
git上的版本，如果树不对称，线条不能保证在中间，如下
![image](https://user-images.githubusercontent.com/18201505/47284453-04091d00-d61a-11e8-9d6a-e96fd5f25214.png)
用的演示的数据，我限定了table的宽度，小于需要的宽度，可能出问题。后来我是调整了persion的间距，从原来的1em调为0.5，暂时解决了这个问题。
现在我想压缩下整体的高度，还没找到合适的调整方法。

**Comment by nidegexing** [comment]
用的chrome。发现不能直接给组件宽度，否则会出现之前提到错位的。
这个组件很好用，谢谢你。

**Comment by tower1229** [comment]
整体宽度不能限制，定宽也需要overflow:auto

**Comment by fmscole** [comment]
我也是这个问题，配偶也是上下显示，npm安装出错，用的是git版本。
![图片](https://user-images.githubusercontent.com/8135902/58310340-009c7500-7e39-11e9-9e99-2172f555b33d.png)

**Comment by fmscole** [comment]
我通过设置.node.hasMate .person:last-child{margin-left:0em;}，已解决

**Comment by tower1229** [comment]
其实就是样式问题，默认的样式可能容纳不了太多文字
